library(shinytest2)

test_that("{shinytest2} recording: my_app", {
  app <- AppDriver$new(name = "my_app", height = 736, width = 1063)
  app$click("link_Home_to_Stat")
  app$set_inputs(y = "total")
  app$expect_values()
  app$set_inputs(x = "Company.Focus")
  app$expect_values()
  app$set_inputs(panels = "Worldmap")
  app$set_inputs(panels = "Value Chain")
  app$set_inputs(countryselect = "United States")
  app$set_inputs(countryselect = c("United States", "Canada"))
  app$set_inputs(panels = "Companies")
  app$set_inputs(Company = "Accellta")
  app$expect_values()
  app$click("link_CI_to_Contact")
  app$set_inputs(panels = "People")
  app$click("link_EI_to_questionaire2")
  app$set_inputs(panels = "Value Chain")
  app$set_inputs(regionselect = c("North America", "Asia Pacific"))
  app$set_inputs(countryselect = "United States")
  app$set_inputs(countryselect = c("United States", "Japan"))
  app$set_inputs(countryselect = c("United States", "Japan", "Canada"))
  app$expect_values()
})
